### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jknutson** [darrylri/weather_station#2]
software
- [ ] add check for hardware SPI enabled

hardware
- [ ] BME680 support
- [ ] DHT22 support
- [ ] DS18B20 support

ui
- [ ] web plotting (adafruitIO or Grafana)
- [ ] at a glance/current readings
